env:
  global:
    - secure: DxPYWw/9IgPaks0BTpHpgZCg0by76c9BXT+ueuCE4c3xzEF0pkNAfj9qY1GV+BwQPwGChoVycwIYwgJPJZDKYAklPWXpZ/daHOiuJC1nlS75868fc5FFQKM60yJhQEUZe+SWhKTAMpj/gX9hRYciSAvaa/oYib070/l6MznLODOgOwwlrkZRsDlyD2BUp26lMt/E/JcKt+I9Zs+g8NNlLrHl7nAjz7U2Ikpo/ksj4+gUz4HzDKC4HR9xBuaTLgSqxq5Q5e8rrfMDNXSxVqBB3qoz1a3KVmg3JxQEVb/TctiSaaXNO9B9ETG1r/N8wRwE1WpLwXSciCl6FoV0Seh6A9wfROLB3fwtKV2jXqaIlcHXKjJ+MEvnxXFfHMDH00cZT0NOxhDfu6WHVjYuhqGUigdN1wAOjIp9BIBWLlzpN2SESMjBFB/xbc4mySEED0K6mCvU+wA0UroLEir7dfcfqNFhPTRa8CAE2ZcChfPjp0W/opF2pupIdCJqVoIjg61D5rPORd4cX2VzsacFleK4yyFbRKTT+cgte9jpplgu9aLihfQgKwWc7pFrf1Bxu8+aUDRad/d06OdRxnfT4xnuHJZE/wHrQqj0GKrmppsM4TbXsj9TTnoKQq/Qu9u08x37RaOn+TKj9uSZRPtvI1vepkOAH/uRPy0SGOevHg5nZTU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/someonewhocares.org
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
