env:
  global:
    - secure: g5UnKL8pDviF4DWYeVHrAdrhh4g+7GLYaAOojOoHCMnbbXjNypbgvwoh9Es/GGdQRPqb0wcWPsydBXLVOFFU1hyZ7jBhDhRI/GuFP5Fk4EvxY9gGQjR/toJ/kNQWo6QTm4ihsAFGj38jcI6ujOGMmTDXAE89KGqhUuO29fyTRpdQDLK1bMEmb78AI3Ym8F/Mu7N/QUIDljXPXz7L7NBGTwSsKo9hXT+DojQGi0G5Elfi11jFYyPMu43OxCDcnnybmO/dLMEPdt/O4htr33VHE4K7bPlU4WwbmWo/Lbg+QvbQ1A9OBZhtp/Hfx9JwpaUHZNl6VzDKXUEYSvRSyNx+i9pDEDJeXxXJFKKzp7la21sB7eRdBpEhG2kDaK+PeR0G46a644ijUqaZeFonDcl2pHMt2IilHE0vRxyr7Fz4iEcVF9MS2OurYEm3k0kG76iZyj72eEXQpOmI6ov32BDXBxw+HiSnB1g4mDnozCztMjl+V4Rs9dCnVYNTYh0L6MkOXILzrLNOOINr6YMi7KOpW2isy8PAQN7qRpCcVI1kOc2wttDwaxHV4K1jl48ABzPqFdNwI8Ts0cEuAjbwJXr35cnMlWhpdDZ6otkmuE+MX+P/GwNqlz7RMM+MqFiN1G/FFxNZwdEK9MEJJrygqsxjTTLfbyPbwxYGyzQOLpm2kLs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/someonewhocares.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
