env:
  global:
    - secure: UzQiEFBX4Y8b3uf4ztk9jNHgKDPE6KyooZStvSrm7x6xZyZi/YjSljXKRZB2dQb/Yqa5Fj9YrJbdMNdwONjIZFi01OnfbYx6aB6KhRopEHwEhJvJWvIqbnxB6D2iQE41aU4AoQOoJwzGPtBSGXWstAsjjhP93VP8ExHh/51EgJwyl0NhTV3151nN++xWp1pvEVCaTOSfGZOdGwl19MIh3P5AVbU+oa3ZU04aT+ei2Q7GnSWlCbYOqHunQMz0oLf2/nZQRWJJhp1F32+0Rzp7Uz3k2tkP06f6VW2KzaQSTc4s5zT7rUYO0cDquD1alk3CCWRypg6OjDaYi6sgAMkxVBGjlJFtYa+jXEppEcdK0RUCCJALu5rOFd8fc0vKRbh2s1NhN4my1e2MmXT7fQMFY4T9oRW0YzficumrmsVIYNDV6OdvGfrKmrgzyGQSnhqIp6df8ChsYMFsQc6Lk4x4JbwGOxPbteKnqGXqriKOEtmP6tCg602Y9hRZsHVr1+4P5hcLrLU6czQZk994592AVjj23OAjiAw3cSJfuUK4ll2gtVOosF/cxskwdKVGYqiMPD9fOjep3/vJQFcvUd0rTs251Gs+bO03FOTU6y2uqDO/jIuZfg0BdUBAFHgGHxOmz0WmH9JlndmXUNEPNL4RASe8nmx+fppr94ycH8GP6+A=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/someonewhocares.org
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
