env:
  global:
    - secure: pxwb0N4TcVABhk//OMTcH+lhzBgy0uu5YBFJX8W10jbTEPEs2r0yiKay4qZUXBNQ7cOwp17aDq2F79r4Ww/k9wZ0Fe+eUoIvzchr3JLGTj6zi1EHh+dCIAwsdEWUUx7bZMAx0ekbd0tyw8rhcuNh8JGji8Cl8oI4LKeGUA/PgP4oyCh0WOWjmbKN4ALZ6Z5Fmr7oRXd2tZcDKW6zuvtm5ljsxEcCoW33zJZyO0ARVJZtVks3OIyzD/LvM3Sk8mR255uk5ZaB4Dho43yQEJKOEnITS4q9jAchTp3A8uOCxsn67q22+Z13TfNX+M4WQJb/ywr3FxmR0ORp7x7bkRLarGVEWorJQIG2zqweFHssw031eQg1hNXqvJGF3LFX2WWS/3dKiiivLMqt0vxy2xP+4jsdm2gEIG4mWlx5PatOFaeIB94epgFdV2GUx7d/94OwTfU9NGwpe20PLkl10NnRd6+mUdZeuYRk3VP58VkZlY/WaFdz5AGFEHjqRGKI0pWz4zGAemRv2cG62XH193ergnqcCkPXlDLiedobMbhlqmd4/0XMg+ZcXdXKvV1aZgHyPVfc7i/p+38HDQQWszzfmUiAXnhhOs7Igg6ERNApnlpnzx7Oqq+n/jBIG3BnyAyryTRSf3+r8eleORrsPMlx/+O2g/WyMnbmeRhsm8y2dnc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/someonewhocares.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
