env:
  global:
    - secure: DFK+107T6mCD+9t9OFnkL27Hiq80khaClw2lO/S3llnqDZOMOVvLavueMYFX4E/kQ09M8ly0jYpW+NdCvU1FZrQoO3kcwgTi1fSomsNYoECL6xC0tjbcS/JuJl0VzAmpc2E/9YbajeKEOcdxoUEmQM80k3+TWViSFN2GyKROgATYC/WU7AtlvYBG11TVcFNVRnazpJXG07Jq+i342PMOc+4I28kqqfVJXZiqVCIOkW6AhpD9n1jUM0jj+CIughSXujEQHv32MwJoPBzb5MDtq82Ois/fc+YQYb/j3KQbeUR4yfRWDuj2XHGHOFfiOpvA8N93F3F7vGM6Ckjk1m8c3UX8KMnC7Er+xntSgBdO0+UMwBNpk8nZm7163Cn6ahIFFKBnIoKTbsvs/jN6fRIFfeGqGXLZNOeXoBdK/p1eDr2iLdRLwIflcJI6HcRsvHA6i/Daov51fgnzprs9DrZZFGhUnuQx43KCCkS1KdJdvj5XGScBAKUBv9EdFCG/tUUzZ5cr+vdrDdo3x1VRampSOFIVsjmPPpw6W4OiE+97ajw4b64dmNREsf09afBbZFqJepql2DqsqYyjixg+lAWM4AMIBp1e0tqF+P3UQebqVI+DKnW3jeX6TrGyL4remzHDGCfCHq59WKAwiUtjc/wR07T+PrB6SUN3CcJ98XjhGnw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/someonewhocares.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
